spring:
  application:
    name: sparrow
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    properties:
      serverZoneId: Asia/Seoul
  sql:
    init:
      schema-locations: classpath:/schema.sql
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
