spring:
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    properties:
      serverZoneId: Asia/Seoul
  sql:
    init:
      schema-locations: classpath:/schema.sql

#logging:
#  level:
#    io.r2dbc.h2: DEBUG
#    org.springframework.r2dbc: DEBUG
#    org.springframework.data.r2dbc: DEBUG
